version: "3"

services:
  vshare:
    build: .
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ~/Desktop:/data
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: helloworld
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./docs/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass helloworld
    ports:
      - "6379:6379"
